[build]
  base = "project"
  command = "npm install -g vite@5.4.2 && npm install vite@5.4.2 @vitejs/plugin-react --save-dev && npm install --legacy-peer-deps && npx vite build --config vite.config.ts"



  publish = "project/dist"

[build.environment]
  NODE_VERSION = "20.9.0"
