[build]
  base = "project"
  command = "npm install -g vite && npm install --legacy-peer-deps && npx vite build --config project/vite.config.ts"
  publish = "project/dist"

[build.environment]
  NODE_VERSION = "20.9.0"
