[build]
  base = "project"
  command = "npm install vite @vitejs/plugin-react --save-dev && npm install --legacy-peer-deps && npx vite build --config project/vite.config.ts"
  publish = "project/dist"

[build.environment]
  NODE_VERSION = "20.9.0"
